name: fiewin-web
region: sgp1
services:
- name: web
  image:
    registry_type: DOCR
    repository: fiewin-registry/fiewin-web
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: PROXY_TARGET
    value: "https://91appw.com"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  cors:
    allow_origins:
    - exact: https://91appw.com
    allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allow_headers:
    - '*'
    max_age: "86400" 