name: fiewin-web
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/fiewin-web
  build_command: npm install && npm run build
  run_command: node server.js
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: PROXY_TARGET
    value: "https://91appw.com"
  routes:
  - path: /
  health_check:
    http_path: /health
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3 