[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"

[deploy.envVars]
NODE_ENV = "production"
PORT = "8080"
PROXY_TARGET = "https://91appw.com" 